### ISSUE TITLE
ExpatError

### ISSUE THREAD

**Issue by AbestSG** [neurabenn/pig_connectivity_bp_preprint#1]
Hello,

I got an error when I ran the 'Fig8.SequentialKL.ipynb'. I not sure how to resolve it.

Thanks,
Si
![Screen Shot 2020-10-15 at 1 18 12 PM](https://user-images.githubusercontent.com/70385215/96164681-92eb6000-0ee9-11eb-9068-fa7b2456db44.png)

**Comment by neurabenn** [comment]
can you check that nibabel is imported correctly? seems to be an issue loading the surface file. Potentially check the route of the file as well?

**Comment by AbestSG** [comment]
> can you check that nibabel is imported correctly? seems to be an issue loading the surface file. Potentially check the route of the file as well?

Hello,

There is no issue when nibabel is imported. The '.gii 'file is also in correct route. 
I also got the same error when I load your '.gii' file using 'nib.load()'.

![Screen Shot 2020-10-15 at 3 01 45 PM](https://user-images.githubusercontent.com/70385215/96174711-b1585800-0ef7-11eb-8747-717e4c0bcd3c.png)

**Comment by neurabenn** [comment]
odd... I'm thinking it might be a permissions error. Could you try loading it in fsleyes or wb_view?

**Comment by AbestSG** [comment]
I got an error when I loaded 'L.rhum.inflated.surf.gii' in fsleyes.

![Screen Shot 2020-10-15 at 4 18 11 PM](https://user-images.githubusercontent.com/70385215/96181827-98a16f80-0f02-11eb-90b5-d43cbb73bd76.png)

**Comment by neurabenn** [comment]
Ok, I'll change permissions and reupload. can you open up the pig surfaces alright?

**Comment by AbestSG** [comment]
> Ok, I'll change permissions and reupload. can you open up the pig surfaces alright?

I could not open the pig surfaces in fsleyes, either. Thanks for your help!
![Screen Shot 2020-10-15 at 4 33 28 PM](https://user-images.githubusercontent.com/70385215/96182983-3f3a4000-0f04-11eb-8c62-565150a3e7d4.png)

**Comment by neurabenn** [comment]
Hi there, I've changed the permissions on the files.  See if you can pull or clone fresh and try opening again please :)

**Comment by neurabenn** [comment]
you can also try doing  a checkout to the master branch

**Comment by neurabenn** [comment]
So it appears it was an issue with git large file storage. I've since uploaded a new version to the master branch. try doing a pull and if that doesn't work clone it new. let me know how it goes please and if It works I'll close the issue.

**Comment by AbestSG** [comment]
> So it appears it was an issue with git large file storage. I've since uploaded a new version to the master branch. try doing a pull and if that doesn't work clone it new. let me know how it goes please and if It works I'll close the issue.

Appreciate it! It working now. 
I have another question about the normalized colorbar. How did you get the R_hmax value for the vmax argument?

Thanks,
Si

![Screen Shot 2020-10-16 at 9 42 15 AM](https://user-images.githubusercontent.com/70385215/96266199-62143500-0f94-11eb-8813-d81d71e86014.png)

**Comment by neurabenn** [comment]
oops, that's just a bit of left over code from when I ran the right hemisphere. you can ignore it.
